version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install deps
          command: |
            pip install cython
            pip install -r requirements.txt
            pip install git+https://github.com/hgrecco/pint.git@f356379c15c1cb5d211c795872ac9e9284d2358f#egg=pint
            pip install pint-pandas-fork
            pip install -r test-requirements.txt
            pip install openpyxl xlrd
      - python/save-cache
      - run:
          name: install eam_core
          command: |
            pip install eam-data-tools
            pip install .
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
