version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: install deps
          command: |
            pip install .
            pip install -r test-requirements.txt
            pip install pytest
      - python/save-cache
      - run:
          command: FLASK_ENV=testing pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
